var myData = {

	"dogs" : [{

		"image": "dachshund.jpg",
		"breed" : "            Dachshund",
		"weight" : 'Weight: Under 11 pounds',
		"height" : "Height: 6 inches",
		"color" : "Color: Any color but white",
		"coat" : "Short, long and Wire haired",
		"activityLevel" : "High",
		"temperament" : "Bold and Playful",
		"learningRate" : "High",
		"obedience" : "Obedience: Medium",
		"guardAbility" : "Low",
		"watchAbility" : "High",
		"lifeSpan" : "Life Span: 10-14 years",
		"origin" : "Origin: Germany",
		"appearance" : "Appearance: \nNicknamed the 'sausage dog,' as it is low to the ground, long in body and short of leg. A full-grown standard dachshund averages 16 to 28 pounds, while the miniature variety typically weighs less than 11 lb.",
		"temperament2" : "Temperament: \nDachshunds are playful, fun dogs, known for their propensity to chase small animals, birds and tennis balls with great determination and ferocity. Many dachshunds are strong-headed or stubborn, making them a challenge to train.",
		"history" : "History: \nSome have theorized that the early roots of the dachshund go back to Ancient Egypt, where engravings were made featuring short-legged hunting dogs."
	}, {
		"image": "Golden_Retriever.jpg",
		"breed" : "            Golden Retriever",
		"weight" : "Weight: Average 65-75 lbs",
		"height" : "Height: 21-24 inches",
		"color" : "Color: Any shades of gold or cream",
		"coat" : "Straight or moderately wavy",
		"activityLevel" : "Medium",
		"temperament" : "Playful",
		"learningRate" : "High",
		"obedience" : "Obedience: High",
		"guardAbility" : "Medium",
		"watchAbility" : "High",
		"lifeSpan" : "Life Span: 10-12 years",
		"origin" : "Origin: Scotland",
		"appearance" : "Appearance: \nThe Golden Retriever is a large, strongly-built breed with a dense water-repellant wavy coat.",
		"temperament2" : "Temperament: \nThe temperament of the Golden Retriever is a hallmark of the breed, and is described in the standard as 'kindly, friendly and confident'. Golden Retrievers make good family pets, particularly as they are patient with children.",
		"history" : "History: \nThe Golden Retriever was originally bred in Scotland in the mid-19th century."
	}, {
		"image": "staffie.jpg",
		"breed" : "            Staffordshire Bull Terrier",
		"weight" : "Weight: 24-37 lbs",
		"height" : "Height: 36-41 cms",
		"color" : "Color: Red, fawn, white, black or blue",
		"coat" : "Smooth",
		"activityLevel" : "High",
		"temperament" : "Medium",
		"learningRate" : "Medium",
		"obedience" : "Obedience: High",
		"guardAbility" : "High",
		"watchAbility" : "High",
		"lifeSpan" : "Life Span: 10-14 years",
		"origin" : "Origin: England",
		"appearance" : "Appearance: \nThe Staffordshire Bull Terrier is a medium-sized, stocky, and very muscular dog, with a similar appearance to the much larger American Staffordshire terrier and American pit bull terrier.",
		"temperament2" : "Temperament: \nAlthough individual differences in personality exist, common traits exist throughout the Staffords. Due to its breeding, and history, the Staffordshire Bull Terrier is known for its character of intelligence, fearlessness and loyalty.",
		"history" : "History: \nAs time went on the modern Staffordshire Bull Terrier breed has become one with a temperament suitable for a pet and companion."
	}, {
		"image": "poodle.jpg",
		"breed" : "            Poodle",
		"weight" : "Weight: 15-25 lbs",
		"height" : "Height: Over 15 inches",
		"color" : "Color: White, pink, black",
		"coat" : "Curly Fur",
		"activityLevel" : "Medium",
		"temperament" : "Playful",
		"learningRate" : "Medium",
		"obedience" : "Obedience: Low",
		"guardAbility" : "Low",
		"watchAbility" : "Low",
		"lifeSpan" : "Life Span: 8-15 years",
		"origin" : "Origin: France",
		"appearance" : "Appearance: \nThe poodle is a an active, intelligent and elegant dog, squarely built, and well proportioned.",
		"temperament2" : "Temperament: \nThe poodle is a an active, intelligent and elegant dog, squarely built, and well proportioned.",
		"history" : "History: \nThe European mainland had known the poodle long before it was brought to England. Drawings by German artist Albrecht Dürer established the popular image of the breed."
	}, {
		"image": "lab.jpg",
		"breed" : "            Labrador Retriever",
		"weight" : "Weight: 55-70 lbs",
		"height" : "Height: 55-62 cm",
		"color" : "Color: Yellow, black, brown",
		"coat" : "Smooth, short, dense and straight",
		"activityLevel" : "High",
		"temperament" : "Bold and Playful",
		"learningRate" : "High",
		"obedience" : "Obedience: High",
		"guardAbility" : "High",
		"watchAbility" : "High",
		"lifeSpan" : "Life Span: 11-16 years",
		"origin" : "Origin: Canada",
		"appearance" : "Appearance: \nLabradors are relatively large, with males typically weighing 65 to 80 lb (29 to 36 kg) and females 55 to 70 lb (25 to 32 kg). Labradors weighing close to or over 100 lb (45 kg) are considered obese or having a major fault.",
		"temperament2" : "Temperament: \nThe AKC describes the Labrador's temperament as a kind, pleasant, outgoing and tractable nature. Labradors' sense of smell allows them to home in on almost any scent and follow the path of its origin.",
		"history" : "History: \nYellow and chocolate pups would occasionally appear (although often culled), until finally gaining acceptance in the 20th century."
	}, {
		"image": "akita.jpg",
		"breed" : "            Akita Inu",
		"weight" : "Weight: 50-150 lbs",
		"height" : "Height: 24-28 inches",
		"color" : "Color: Red, brindle, or white",
		"coat" : "Double coat",
		"activityLevel" : "High",
		"temperament" : "Trustworthy, Playful",
		"learningRate" : "Medium",
		"obedience" : "Medium",
		"guardAbility" : "Low",
		"watchAbility" : "Medium",
		"lifeSpan" : "Life Span: 10 years",
		"origin" : "Origin: Japan",
		"appearance" : "Appearance: \nAs a spitz breed, the appearance of the Akita reflects cold weather adaptations essential to their original function.",
		"temperament2" : "Temperament: \nIt is territorial about its property, and can be reserved with strangers.",
		"history" : "History: \nAkita developed primarily from dogs in the northernmost region of the island of Honshū in the Akita prefecture, thus providing the breed's name."
	}, {
		"image": "Basset.jpg",
		"breed" : "            Basset Hound",
		"weight" : "Weight: 45-75 lbs",
		"height" : "Height: 11-15 inches",
		"color" : "Color: Generally black, white and tan",
		"coat" : "Smooth, short and close",
		"activityLevel" : "Low",
		"temperament" : "Friendly, Playful",
		"learningRate" : "Medium",
		"obedience" : "Obedience: Medium",
		"guardAbility" : "Low",
		"watchAbility" : "High",
		"lifeSpan" : "Life Span: 11-12 years",
		"origin" : "Origin: Great Britain",
		"appearance" : "Appearance: \nBassets are large, short, solid and long, with curved sabre tails held high over their long backs.",
		"temperament2" : "Temperament: \nThe Basset Hound is a friendly, outgoing, and playful dog. They are excellent companions for children because of their patient nature and tolerance.",
		"history" : "History: \nThe earliest-known depictions of short-legged hunting dogs are engravings from the Middle Kingdom of Egypt."
	}, {
		"image": "beagle.jpg",
		"breed" : "            Beagle",
		"weight" : "Weight: 20-25 lbs",
		"height" : "Height: 13-16 inches",
		"color" : "Color: Tricolor ",
		"coat" : "Short haired, hard coat of medium length",
		"activityLevel" : "Medium",
		"temperament" : "Even temper",
		"learningRate" : "High",
		"obedience" : "Obedience; High",
		"guardAbility" : "Low",
		"watchAbility" : "Medium",
		"lifeSpan" : "Life Span: 12-15 years",
		"origin" : "Origin: Great Britain",
		"appearance" : "Appearance: \nThe general appearance of the Beagle resembles a miniature Foxhound, but the head is broader and the muzzle shorter, the expression completely different and the legs shorter in proportion to the body.",
		"temperament2" : "Temperament: \nThe Beagle has an even temper and gentle disposition. Described in several breed standards as 'merry', they are amiable and typically neither aggressive nor timid, although this depends on the individual.",
		"history" : "History: \nAlthough beagle-type dogs have existed for over 2,000 years, the modern breed was developed in Great Britain around the 1830s from several breeds, including the Talbot Hound."
	}, {
		"image": "border.jpg",
		"breed" : "            Border Collie",
		"weight" : "Weight: 27-45 lbs",
		"height" : "Height: 18-22 inches",
		"color" : "Color: Solid coloured, bicoloured",
		"coat" : "Smooth or rough Double Coat",
		"activityLevel" : "High",
		"temperament" : "Intelligent",
		"learningRate" : "Medium",
		"obedience" : "Obedience; High",
		"guardAbility" : "Medium",
		"watchAbility" : "Medium",
		"lifeSpan" : "Life Span: 10-17 years",
		"origin" : "Origin: United Kingdom",
		"appearance" : "Appearance: \nIn general, Border Collies are medium-sized dogs with a moderate amount of coat, which is often thick and frequently sheds. Their double coats vary from smooth to rough, and come in many colours.",
		"temperament2" : "Temperament: \nBorder Collies require considerable daily physical exercise and mental stimulation. The Border Collie is an intelligent dog breed; in fact, it is widely considered to be the most intelligent dog breed.",
		"history" : "History: \nThe Border Collie is descended from landrace collies, a type found widely in the British Isles. The name for the breed came from its probable place of origin along the Anglo-Scottish border."
	}, {
		"image": "dalmatian.jpg",
		"breed" : "            Dalmatian",
		"weight" : "Weight: 36-70 lbs",
		"height" : "Height: 18-26 inches",
		"color" : "Color: White with black spots",
		"coat" : "White background",
		"activityLevel" : "High",
		"temperament" : "Playful, Energetic",
		"learningRate" : "High",
		"obedience" : "Obedience: High",
		"guardAbility" : "Medium",
		"watchAbility" : "High",
		"lifeSpan" : "Life Span: 10-13 years",
		"origin" : "Origin: Croatia",
		"appearance" : "Appearance: \nThe Dalmatian is a mid-sized, well-defined, muscular dog with excellent endurance and stamina.",
		"temperament2" : "Temperament: \nThey were used as dogs of war, guarding the borders of Dalmatia. To this day, the breed retains a high guarding instinct; although friendly and loyal to those the dog knows and trusts, it is often aloof with strangers and unknown dogs.",
		"history" : "History: \nThe first illustrations of the dog have been found in Croatia: an altar painting in Veli Lošinj dating to 1600–1630, and a fresco in Zaostrog."
	}, {
		"image": "puli.jpg",
		"breed" : "            Puli",
		"weight" : "Weight: 23-30 lbs",
		"height" : "Height: 16-18 inches",
		"color" : "Color: Black, gray, white",
		"coat" : "Dreadlocks",
		"activityLevel" : "Medium",
		"temperament" : "Playful",
		"learningRate" : "High",
		"obedience" : "Obedience: Medium",
		"guardAbility" : "Low",
		"watchAbility" : "Low",
		"lifeSpan" : "Life Span: 10-16 years",
		"origin" : "Origin; Hungary",
		"appearance" : "Appearance: \nThe Puli is a solid colored dog that is usually black. Other less common coat colors are white, gray, or cream.",
		"temperament2" : "Temperament: \nPulis are intelligent, agile dogs. Despite their bulky appearance and very thick coat they are very fast, agile and able to change directions instantly.",
		"history" : "History: \nThe Puli is an ancient sheepdog, from Hungary, introduced by the migration of the Magyars from Central Asia more than 1,000 years ago."
	}, {
		"image": "rott.jpg",
		"breed" : "            Rottweiler",
		"weight" : "Weight: 77-130 lbs",
		"height" : 'Height: 22-27 inches',
		"color" : "Color: Black with tan",
		"coat" : "Double coated, Short, hard and thick",
		"activityLevel" : "Medium",
		"temperament" : "Hard Working",
		"learningRate" : "Medium",
		"obedience" : "Obedience: Medium",
		"guardAbility" : "High",
		"watchAbility" : "High",
		"lifeSpan" : "Life Span: 9-10 years",
		"origin" : "Origin: Germany",
		"appearance" : "Appearance: \nThis breed is all about balance, endurance, proportionality, intelligence and strength. The standards in place for the Rottweiler's physical appearance by the American Kennel Club mimic these characteristics.",
		"temperament2" : "Temperament: \nAccording to the FCI Standard, the Rottweiler is good-natured, placid in basic disposition, very devoted, obedient, biddable and eager to work.",
		"history" : "History: \nAlthough a versatile breed used in recent times for many purposes, the Rottweiler is one of the oldest of herding breeds. A multi-faceted herding and stock protection dog."
	}, {
		"image": "husky.jpg",
		"breed" : '            Siberian Husky',
		"weight" : "Weight: 35-60 lbs",
		"height" : "Height: 20-25 inches",
		"color" : "Color: All colors from black to white",
		"coat" : "Thick Double Coat",
		"activityLevel" : "High",
		"temperament" : "Active, Playful",
		"learningRate" : "High",
		"obedience" : "Obedience: High",
		"guardAbility" : "High",
		"watchAbility" : "High",
		"lifeSpan" : "Life Span: 12-14 years",
		"origin" : "Origin: Siberia",
		"appearance" : "Appearance: \nA Siberian Husky's coat is thicker than most other dog breeds, comprising two layers: a dense undercoat and a longer topcoat of short, straight guard hairs.",
		"temperament2" : "Temperament: \nHuskies are an active, energetic, and resilient breed whose ancestors came from the extremely cold and harsh environment of the Siberian Arctic. Siberian Huskies were bred by the Chukchi of Northeastern Asia.",
		"history" : "History: \nThe Siberian Husky, Samoyed, and Alaskan Malamute are all breeds directly descended from the original sled dog, which 2004 DNA analysis confirms is one of the oldest breeds."
	}, {
		"image": "chi.jpg",
		"breed" : "            Chihuahua",
		"weight" : "Weight: 4-10 lbs",
		"height" : "Height: 6-10 inches",
		"color" : "Color: White, black, tan",
		"coat" : 'Smooth and long-haired',
		"activityLevel" : "Medium",
		"temperament" : "Fierce, Loyal",
		"learningRate" : "Low",
		"obedience" : "Obedience: Low",
		"guardAbility" : 'Low',
		"watchAbility" : "Low",
		"lifeSpan" : "Life Span: 15-20 years",
		"origin" : "Origin: Mexico",
		"appearance" : "Appearance: \nTypically, the breed standard for both the long and short coat chihuahua will be identical except for the description of the coat. Chihuahuas have large, round eyes and large, erect ears, set in a high, rounded skull.",
		"temperament2" : "Temperament: \nThe temperament of its human guardian can make a difference in the temperament of the pup. ",
		"history" : "History: \nThe Chihuahua’s history is puzzling and there are many theories surrounding the origin of the breed."
	}, {
		"image": "doge.jpg",
		"breed" : "            Shiba Inu",
		"weight" : "Weight: 20-30 lbs",
		"height" : "Height: 13-17 inches",
		"color" : "Color: Red, sesame, black and tan",
		"coat" : "Double Coat",
		"activityLevel" : "High",
		"temperament" : "Playful",
		"learningRate" : "Medium",
		"obedience" : "Obedience: High",
		"guardAbility" : "Medium",
		"watchAbility" : "Medium",
		"lifeSpan" : "Life Span: 12-15 years",
		"origin" : "Origin: Japan",
		"appearance" : "Appearance: \nThe Shiba's frame is compact with well-developed muscles. Usually appears as a redish orange color and a lot of time associatted with the doge meme.",
		"temperament2" : "Temperament: \nShiba's tend to exhibit an independent nature and sometimes show dog aggression. This is more prevalent between female Shibas and is influenced by the breed's strong prey drive.",
		"history" : "History: \nOriginally, the Shiba Inu was bred to hunt and flush small game, such as birds and rabbits. The Shiba nearly became extinct during World War II due to food shortage."
	}]

};

exports.myData = myData;
